//PRODUCTS
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

//OFFERINGS
export const RECEIVE_OFFERINGS = 'RECEIVE_OFFERINGS'
export const RECEIVE_FILTERS = 'RECEIVE_FILTERS'
export const GET_OFFERING = 'GET_OFFERING'
export const CLEAR_CURRENT_OFFERING = 'CLEAR_CURRENT_OFFERING'
export const CREATE_OFFERING = 'CREATE_OFFERING'
export const EDIT_OFFERING = 'EDIT_OFFERING'
export const EDIT_OFFERING_FILTERS = 'EDIT_OFFERING_FILTERS'
export const UPDATE_OFFERING_STATUS = 'UPDATE_OFFERING_STATUS'

//PROMO-CODES
export const RECEIVE_PROMO_CODES = 'RECEIVE_PROMO_CODES'
export const SEARCH_PROMO_CODES = 'SEARCH_PROMO_CODES'
export const CREATE_PROMO_CODE = 'CREATE_PROMO_CODE'
export const UPLOAD_PROMO_CODES = 'UPLOAD_PROMO_CODES'
export const EDIT_PROMO_CODE = 'EDIT_PROMO_CODE'
export const UPDATE_PROMO_CODE_STATUS = 'UPDATE_PROMO_CODE_STATUS'

//MAINTENANCE
export const RECEIVE_ERRORS = 'RECEIVE_ERRORS'
export const GET_ERROR = 'GET_ERROR'
export const CLEAR_CURRENT_ERROR = 'CLEAR_CURRENT_ERROR'
export const UPDATE_ERROR_STATUS = 'UPDATE_ERROR_STATUS'
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM'
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM'
export const SELECT_ALL = 'SELECT_ALL'
export const UNSELECT_ALL = 'UNSELECT_ALL'

//LOGIN
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

//MODAL
export const HANDLE_MODAL = 'HANDLE_MODAL'

//LOADING
export const START_FETCHING = 'START_FETCHING'
export const END_FETCHING = 'END_FETCHING'
export const START_SAVING= 'START_SAVING'
export const END_SAVING = 'END_SAVING'

//ORDERS
export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER'
export const GET_MERCHANTS_DOCUMENT = 'GET_MERCHANTS'
export const GET_CROSS_MERCHANT_ORDER = 'GET_CROSS_MERCHANT_ORDER'
export const GET_QUALIFICATION_ORDER = 'GET_QUALIFICATION_ORDER'
export const GET_CLEAR_ORDER = 'GET_CLEAR_ORDER'

//ADAPTERS
export const GET_ADAPTER_GERENCIAL_MERCHANT = 'GET_ADAPTER_GERENCIAL_MERCHANT'
export const GET_ADAPTER_SIEBEL_ORDER = 'GET_ADAPTER_SIEBEL_ORDER'
export const GET_ADAPTER_SIEBEL_MERCHANT = 'GET_ADAPTER_SIEBEL_MERCHANT'
export const GET_ADAPTER_SAP_ORDER = 'GET_ADAPTER_SAP_ORDER'
export const GET_ADAPTER_SAP_MERCHANT = 'GET_ADAPTER_SAP_MERCHANT'

//FULLFILMENTS
export const GET_FULLFILMENTS_INTERNAL_ORDER =  'GET_FULLFILMENTS_INTERNAL_ORDER'
export const GET_FULLFILMENTS_INTERNAL_MERCHANT =  'GET_FULLFILMENTS_INTERNAL_MERCHANT'
export const GET_FULLFILMENTS_SALE_ORDER = 'GET_FULLFILMENTS_SALE_ORDER'
export const GET_FULLFILMENTS_RENT_ORDER = 'GET_FULLFILMENTS_RENT_ORDER'