//TECHNIQUES
export const RECEIVE_TECHNIQUES = 'RECEIVE_TECHNIQUES'
export const GET_TECHNIQUE = 'GET_TECHNIQUE'
export const CREATE_TECHNIQUE = 'CREATE_TECHNIQUE'
export const EDIT_TECHNIQUE = 'EDIT_TECHNIQUE'
export const DELETE_TECHNIQUE = 'DELETE_TECHNIQUE'

//PRODUCTS
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

//OFFERINGS
export const RECEIVE_OFFERINGS = 'RECEIVE_OFFERINGS'
export const RECEIVE_FILTERS = 'RECEIVE_FILTERS'
export const GET_OFFERING = 'GET_OFFERING'
export const CLEAR_CURRENT_OFFERING = 'CLEAR_CURRENT_OFFERING'
export const CREATE_OFFERING = 'CREATE_OFFERING'
export const EDIT_OFFERING = 'EDIT_OFFERING'
export const EDIT_OFFERING_FILTERS = 'EDIT_OFFERING_FILTERS'
export const UPDATE_OFFERING_STATUS = 'UPDATE_OFFERING_STATUS'

//LOGIN
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

//MODAL
export const HANDLE_MODAL = 'HANDLE_MODAL'

//LOADING
export const START_FETCHING = 'START_FETCHING'
export const END_FETCHING = 'END_FETCHING'
export const START_SAVING= 'START_SAVING'
export const END_SAVING = 'END_SAVING'