import React, { Component, Fragment } from 'react'
import PropTypes from 'prop-types'
import { Field, reduxForm } from 'redux-form'
import { connect } from 'react-redux'

//components
import { InlineField } from '../../components/common/form'
import Button from '../../components/common/Button'
import DateTime from '../../components/common/Calendar/DateTime'

class SearchForm extends Component{

    static propTypes ={
        handleSubmit: PropTypes.func.isRequired
    }

    state = {
        originalQueueSelect: true,
        originalExchangeSelect: true,
        serviceNameSelect: true
    }

    toogleType = (attr) => {
        let newState = this.state
        newState[attr] = !newState[attr]
        this.setState(newState)
    }

    render(){
        const { formData, handleSubmit } = this.props
        const { originalQueueSelect, serviceNameSelect, originalExchangeSelect } = this.state
        
        const formConfig = {
            originalMessage: {
                label: 'originalMessage',
                name: 'originalMessage',
                type: 'text',
                placeholder: ''
            },
            error: {
                label: 'error',
                name: 'error',
                type: 'text',
                placeholder: ''
            },
            statusReprocess: {
                label: 'statusReprocess',
                name: 'statusReprocess',
                type: 'select',
                placeholder: '',
                options:[
                    {value:'', text:'Todos'},
                    {value:'OK', text:'OK'},
                    {value:'NOK', text:'NOK'},
                    {value:'CANCEL', text:'CANCEL'}
                ]
            },
            errorDate: {
                label: 'errorDate (início e fim)',
                name: 'errorDate',
            },
            serviceName: {
                label: <Fragment>serviceName <input type="checkbox" onChange={() => this.toogleType('serviceNameSelect')} title="Mudar para campo de Texto"></input></Fragment>,
                name: 'serviceName',
                type: serviceNameSelect ? 'select' : 'text',
                placeholder: '',
                options:[
                    {value:'', text:'Todos'},
                    {value: "adapter-ativacao-terminal-ms", text: "adapter-ativacao-terminal-ms"},
                    {value: "adapter-desativacao-gerencial-ms", text: "adapter-desativacao-gerencial-ms"},
                    {value: "adapter-desativacao-terminal-ms", text: "adapter-desativacao-terminal-ms"},
                    {value: "adapter-gerencial-ms", text: "adapter-gerencial-ms"},
                    {value: "adapter-plataforma-digital-ms", text: "adapter-plataforma-digital-ms"},
                    {value: "adapter-sap-ms", text: "adapter-sap-ms"},
                    {value: "adapter-siebel-ms", text: "adapter-siebel-ms"},
                    {value: "agreement-integration-ms", text: "agreement-integration-ms"},
                    {value: "agreement-ms", text: "agreement-ms"},
                    {value: "audit-agent-publisher-ms", text: "audit-agent-publisher-ms"},
                    {value: "audit-agent-rabbit-subscriber-ms", text: "audit-agent-rabbit-subscriber-ms"},
                    {value: "audit-agent-subscriber-ms", text: "audit-agent-subscriber-ms"},
                    {value: "auth-ms", text: "auth-ms"},
                    {value: "bank-ms", text: "bank-ms"},
                    {value: "buyer-ms", text: "buyer-ms"},
                    {value: "cancel-ms", text: "cancel-ms"},
                    {value: "contract-ms", text: "contract-ms"},
                    {value: "delivery-order-ms", text: "delivery-order-ms"},
                    {value: "domain-ms", text: "domain-ms"},
                    {value: "enrichment-ms", text: "enrichment-ms"},
                    {value: "fulfillment-internal-ms", text: "fulfillment-internal-ms"},
                    {value: "fulfillment-logical-terminal-ms", text: "fulfillment-logical-terminal-ms"},
                    {value: "fulfillment-rent-ms", text: "fulfillment-rent-ms"},
                    {value: "fulfillment-sale-ms", text: "fulfillment-sale-ms"},
                    {value: "g2-integration-ms", text: "g2-integration-ms"},
                    {value: "maintenance-ms", text: "maintenance-ms"},
                    {value: "media-ms", text: "media-ms"},
                    {value: "media-storage-ms", text: "media-storage-ms"},
                    {value: "merchant-account-ms", text: "merchant-account-ms"},
                    {value: "merchant-ms", text: "merchant-ms"},
                    {value: "offering-ms", text: "offering-ms"},
                    {value: "order-ms", text: "order-ms"},
                    {value: "product-ms", text: "product-ms"},
                    {value: "promo-code-ms", text: "promo-code-ms"},
                    {value: "qualification-merchant-ms", text: "qualification-merchant-ms"},
                    {value: "qualification-ms", text: "qualification-ms"},
                    {value: "qualification-risk-ms", text: "qualification-risk-ms"},
                    {value: "receivable-ms", text: "receivable-ms"}
                ]
            },
            originalExchange: {
                label: <Fragment>originalExchange <input type="checkbox" onChange={() => this.toogleType('originalExchangeSelect')} title="Mudar para campo de Texto"></input></Fragment>,
                name: 'originalExchange',
                type: originalExchangeSelect ? 'select' : 'text',
                placeholder: '',
                options:[
                    {value:'', text:'Todos'},
                    {value: "x-adapter-ativacao-created", text: "x-adapter-ativacao-created"},
                    {value: "x-adapter-ativacao-terminal-delay-error-exchange", text: "x-adapter-ativacao-terminal-delay-error-exchange"},
                    {value: "x-adapter-desativacao-gerencial-delay-error-exchange", text: "x-adapter-desativacao-gerencial-delay-error-exchange"},
                    {value: "x-adapter-desativacao-terminal-cancel-terminal-requested-delay-error-exchange", text: "x-adapter-desativacao-terminal-cancel-terminal-requested-delay-error-exchange"},
                    {value: "x-adapter-gerencial-maintenance-buyer-approved", text: "x-adapter-gerencial-maintenance-buyer-approved"},
                    {value: "x-adapter-gerencial-maintenance-fulfillment-internal-created", text: "x-adapter-gerencial-maintenance-fulfillment-internal-created"},
                    {value: "x-adapter-gerencial-maintenance-merchant-approved", text: "x-adapter-gerencial-maintenance-merchant-approved"},
                    {value: "x-adapter-plataforma-digital-delay-error-exchange", text: "x-adapter-plataforma-digital-delay-error-exchange"},
                    {value: "x-adapter-sap-maintenance-fulfillment-sale-created", text: "x-adapter-sap-maintenance-fulfillment-sale-created"},
                    {value: "x-adapter-sap-maintenance-order-cancel-requested", text: "x-adapter-sap-maintenance-order-cancel-requested"},
                    {value: "x-adapter-sap-maintenance-order-payment-cancel-registered", text: "x-adapter-sap-maintenance-order-payment-cancel-registered"},
                    {value: "x-adapter-sap-maintenance-order-payment-required", text: "x-adapter-sap-maintenance-order-payment-required"},
                    {value: "x-adapter-sap-maintenance-order-rejected", text: "x-adapter-sap-maintenance-order-rejected"},
                    {value: "x-adapter-sap-maintenance-order-submitted", text: "x-adapter-sap-maintenance-order-submitted"},
                    {value: "x-adapter-siebel-maintenance-buyer-establishment-code-created", text: "x-adapter-siebel-maintenance-buyer-establishment-code-created"},
                    {value: "x-adapter-siebel-maintenance-delivery-order-tracking-changed", text: "x-adapter-siebel-maintenance-delivery-order-tracking-changed"},
                    {value: "x-adapter-siebel-maintenance-establishment-code-created", text: "x-adapter-siebel-maintenance-establishment-code-created"},
                    {value: "x-adapter-siebel-maintenance-fulfillment-rent-created", text: "x-adapter-siebel-maintenance-fulfillment-rent-created"},
                    {value: "x-adapter-siebel-maintenance-order-approved", text: "x-adapter-siebel-maintenance-order-approved"},
                    {value: "x-adapter-siebel-maintenance-order-cancel-requested", text: "x-adapter-siebel-maintenance-order-cancel-requested"},
                    {value: "x-adapter-siebel-maintenance-order-canceled", text: "x-adapter-siebel-maintenance-order-canceled"},
                    {value: "x-adapter-siebel-maintenance-order-closed", text: "x-adapter-siebel-maintenance-order-closed"},
                    {value: "x-adapter-siebel-maintenance-order-payment-required", text: "x-adapter-siebel-maintenance-order-payment-required"},
                    {value: "x-adapter-siebel-maintenance-order-rejected", text: "x-adapter-siebel-maintenance-order-rejected"},
                    {value: "x-adapter-siebel-maintenance-payment-transaction-processed", text: "x-adapter-siebel-maintenance-payment-transaction-processed"},
                    {value: "x-agreement", text: "x-agreement"},
                    {value: "x-agreement-merchant-pending-delay-error-exchange", text: "x-agreement-merchant-pending-delay-error-exchange"},
                    {value: "x-agreement-qualification-merchant-pending-delay-error-exchange", text: "x-agreement-qualification-merchant-pending-delay-error-exchange"},
                    {value: "x-audit-change-stream-created", text: "x-audit-change-stream-created"},
                    {value: "x-buyer-approved", text: "x-buyer-approved"},
                    {value: "x-buyer-delay-error-exchange", text: "x-buyer-delay-error-exchange"},
                    {value: "x-buyer-establishment-code-created", text: "x-buyer-establishment-code-created"},
                    {value: "x-cancel-requested", text: "x-cancel-requested"},
                    {value: "x-cancel-resource-requested", text: "x-cancel-resource-requested"},
                    {value: "x-cancel-terminal-requested", text: "x-cancel-terminal-requested"},
                    {value: "x-delivery-order-fulfillment-internal-created-delay-error-exchange", text: "x-delivery-order-fulfillment-internal-created-delay-error-exchange"},
                    {value: "x-delivery-order-fulfillment-item-product-processed-delay-error-exchange", text: "x-delivery-order-fulfillment-item-product-processed-delay-error-exchange"},
                    {value: "x-delivery-order-fulfillment-logical-terminal-created-delay-error-exchange", text: "x-delivery-order-fulfillment-logical-terminal-created-delay-error-exchange"},
                    {value: "x-delivery-order-fulfillment-processed-delay-error-exchange", text: "x-delivery-order-fulfillment-processed-delay-error-exchange"},
                    {value: "x-delivery-order-fulfillment-rent-created-delay-error-exchange", text: "x-delivery-order-fulfillment-rent-created-delay-error-exchange"},
                    {value: "x-delivery-order-fulfillment-sale-created-delay-error-exchange", text: "x-delivery-order-fulfillment-sale-created-delay-error-exchange"},
                    {value: "x-delivery-order-order-approved-delay-error-exchange", text: "x-delivery-order-order-approved-delay-error-exchange"},
                    {value: "x-delivery-order-order-canceled-delay-error-exchange", text: "x-delivery-order-order-canceled-delay-error-exchange"},
                    {value: "x-delivery-order-order-payment-cancel-requested-delay-error-exchange", text: "x-delivery-order-order-payment-cancel-requested-delay-error-exchange"},
                    {value: "x-delivery-order-order-payment-registered-delay-error-exchange", text: "x-delivery-order-order-payment-registered-delay-error-exchange"},
                    {value: "x-delivery-order-order-payment-required-delay-error-exchange", text: "x-delivery-order-order-payment-required-delay-error-exchange"},
                    {value: "x-delivery-order-order-payment-unidentified-delay-error-exchange", text: "x-delivery-order-order-payment-unidentified-delay-error-exchange"},
                    {value: "x-delivery-order-order-qualified-delay-error-exchange", text: "x-delivery-order-order-qualified-delay-error-exchange"},
                    {value: "x-delivery-order-order-rejected-delay-error-exchange", text: "x-delivery-order-order-rejected-delay-error-exchange"},
                    {value: "x-delivery-order-order-submitted-delay-error-exchange", text: "x-delivery-order-order-submitted-delay-error-exchange"},
                    {value: "x-delivery-order-payment-transaction-processed-delay-error-exchange", text: "x-delivery-order-payment-transaction-processed-delay-error-exchange"},
                    {value: "x-delivery-order-processed", text: "x-delivery-order-processed"},
                    {value: "x-delivery-order-tracking-changed", text: "x-delivery-order-tracking-changed"},
                    {value: "x-establishment-code-created", text: "x-establishment-code-created"},
                    {value: "x-establishment-code-created-delay-error-exchange", text: "x-establishment-code-created-delay-error-exchange"},
                    {value: "x-fulfillment-internal-created", text: "x-fulfillment-internal-created"},
                    {value: "x-fulfillment-internal-fulfillment-internal-processed-delay-error-exchange", text: "x-fulfillment-internal-fulfillment-internal-processed-delay-error-exchange"},
                    {value: "x-fulfillment-internal-order-approved-delay-error-exchange", text: "x-fulfillment-internal-order-approved-delay-error-exchange"},
                    {value: "x-fulfillment-internal-processed", text: "x-fulfillment-internal-processed"},
                    {value: "x-fulfillment-item-product-processed", text: "x-fulfillment-item-product-processed"},
                    {value: "x-fulfillment-logical-terminal-created", text: "x-fulfillment-logical-terminal-created"},
                    {value: "x-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-delay-error-exchange", text: "x-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-delay-error-exchange"},
                    {value: "x-fulfillment-logical-terminal-order-approved-delay-error-exchange", text: "x-fulfillment-logical-terminal-order-approved-delay-error-exchange"},
                    {value: "x-fulfillment-logical-terminal-processed", text: "x-fulfillment-logical-terminal-processed"},
                    {value: "x-fulfillment-processed", text: "x-fulfillment-processed"},
                    {value: "x-fulfillment-rent-created", text: "x-fulfillment-rent-created"},
                    {value: "x-fulfillment-rent-maintenance-fulfillment-rent-processed", text: "x-fulfillment-rent-maintenance-fulfillment-rent-processed"},
                    {value: "x-fulfillment-rent-maintenance-order-approved", text: "x-fulfillment-rent-maintenance-order-approved"},
                    {value: "x-fulfillment-rent-processed", text: "x-fulfillment-rent-processed"},
                    {value: "x-fulfillment-sale-created", text: "x-fulfillment-sale-created"},
                    {value: "x-fulfillment-sale-fulfillment-sale-processed-delay-error-exchange", text: "x-fulfillment-sale-fulfillment-sale-processed-delay-error-exchange"},
                    {value: "x-fulfillment-sale-order-approved-delay-error-exchange", text: "x-fulfillment-sale-order-approved-delay-error-exchange"},
                    {value: "x-fulfillment-sale-processed", text: "x-fulfillment-sale-processed"},
                    {value: "x-maintenance-error-events", text: "x-maintenance-error-events"},
                    {value: "x-marketplace-integration-maintenance-canceled", text: "x-marketplace-integration-maintenance-canceled"},
                    {value: "x-marketplace-integration-maintenance-processed", text: "x-marketplace-integration-maintenance-processed"},
                    {value: "x-marketplace-integration-tracking-changed", text: "x-marketplace-integration-tracking-changed"},
                    {value: "x-merchant-accepted", text: "x-merchant-accepted"},
                    {value: "x-merchant-approved", text: "x-merchant-approved"},
                    {value: "x-merchant-changed", text: "x-merchant-changed"},
                    {value: "x-merchant-delay-error-exchange", text: "x-merchant-delay-error-exchange"},
                    {value: "x-merchant-pending", text: "x-merchant-pending"},
                    {value: "x-merchant-qualified", text: "x-merchant-qualified"},
                    {value: "x-merchant-qualified-delay-error-exchange", text: "x-merchant-qualified-delay-error-exchange"},
                    {value: "x-merchant-rejected", text: "x-merchant-rejected"},
                    {value: "x-merchant-reproved", text: "x-merchant-reproved"},
                    {value: "x-merchant-submitted", text: "x-merchant-submitted"},
                    {value: "x-order-approved", text: "x-order-approved"},
                    {value: "x-order-cancel-requested", text: "x-order-cancel-requested"},
                    {value: "x-order-canceled", text: "x-order-canceled"},
                    {value: "x-order-cancelment-allowed", text: "x-order-cancelment-allowed"},
                    {value: "x-order-cancelment-allowed-delay-error-exchange", text: "x-order-cancelment-allowed-delay-error-exchange"},
                    {value: "x-order-closed", text: "x-order-closed"},
                    {value: "x-order-item-changed", text: "x-order-item-changed"},
                    {value: "x-order-item-changed-delay-error-exchange", text: "x-order-item-changed-delay-error-exchange"},
                    {value: "x-order-item-processed", text: "x-order-item-processed"},
                    {value: "x-order-items-canceled", text: "x-order-items-canceled"},
                    {value: "x-order-payment-cancel-registered", text: "x-order-payment-cancel-registered"},
                    {value: "x-order-payment-cancel-requested", text: "x-order-payment-cancel-requested"},
                    {value: "x-order-payment-pending", text: "x-order-payment-pending"},
                    {value: "x-order-payment-registered", text: "x-order-payment-registered"},
                    {value: "x-order-payment-registered-delay-error-exchange", text: "x-order-payment-registered-delay-error-exchange"},
                    {value: "x-order-payment-required", text: "x-order-payment-required"},
                    {value: "x-order-payment-unidentified-delay-error-exchange", text: "x-order-payment-unidentified-delay-error-exchange"},
                    {value: "x-order-qualified", text: "x-order-qualified"},
                    {value: "x-order-qualified-delay-error-exchange", text: "x-order-qualified-delay-error-exchange"},
                    {value: "x-order-rejected", text: "x-order-rejected"},
                    {value: "x-order-submitted", text: "x-order-submitted"},
                    {value: "x-payment-transaction-processed", text: "x-payment-transaction-processed"},
                    {value: "x-payment-unidentified", text: "x-payment-unidentified"},
                    {value: "x-qualification-buyer-establishment-code-created-delay-error-exchange", text: "x-qualification-buyer-establishment-code-created-delay-error-exchange"},
                    {value: "x-qualification-merchant-agreement-delay-error-exchange", text: "x-qualification-merchant-agreement-delay-error-exchange"},
                    {value: "x-qualification-merchant-pending", text: "x-qualification-merchant-pending"},
                    {value: "x-qualification-order-submitted-delay-error-exchange", text: "x-qualification-order-submitted-delay-error-exchange"},
                    {value: "x-receivables-maintenance-order-canceled", text: "x-receivables-maintenance-order-canceled"},
                    {value: "x-receivables-maintenance-order-items-canceled", text: "x-receivables-maintenance-order-items-canceled"},
                    {value: "x-receivables-maintenance-order-payment-required", text: "x-receivables-maintenance-order-payment-required"},
                    {value: "x-receivables-maintenance-order-rejected", text: "x-receivables-maintenance-order-rejected"},
                    {value: "x-resource-canceled", text: "x-resource-canceled"},
                    {value: "x-terminal-canceled", text: "x-terminal-canceled"}
                ]
            },
            originalQueue: {
                label: <Fragment>originalQueue <input type="checkbox" onChange={() => this.toogleType('originalQueueSelect')} title="Mudar para campo de Texto"></input></Fragment>,
                name: 'originalQueue',
                type: originalQueueSelect ? 'select' : 'text',
                placeholder: '',
                options: [
                    {value:'', text:'Todos'},
                    {value: "x-adapter-ativacao-terminal-delay-error-exchange.q-adapter-ativacao-terminal-error-ack-reply", text: "x-adapter-ativacao-terminal-delay-error-exchange.q-adapter-ativacao-terminal-error-ack-reply"},
                    {value: "x-adapter-ativacao-terminal-delay-error-exchange.q-adapter-ativacao-terminal-error-retry", text: "x-adapter-ativacao-terminal-delay-error-exchange.q-adapter-ativacao-terminal-error-retry"},
                    {value: "x-adapter-desativacao-gerencial-delay-error-exchange.q-adapter-desativacao-gerencial-error-ack-reply", text: "x-adapter-desativacao-gerencial-delay-error-exchange.q-adapter-desativacao-gerencial-error-ack-reply"},
                    {value: "x-adapter-desativacao-gerencial-delay-error-exchange.q-adapter-desativacao-gerencial-error-retry", text: "x-adapter-desativacao-gerencial-delay-error-exchange.q-adapter-desativacao-gerencial-error-retry"},
                    {value: "x-adapter-desativacao-terminal-cancel-terminal-requested-delay-error-exchange.q-adapter-desativacao-terminal-cancel-terminal-requested-error-ack-reply", text: "x-adapter-desativacao-terminal-cancel-terminal-requested-delay-error-exchange.q-adapter-desativacao-terminal-cancel-terminal-requested-error-ack-reply"},
                    {value: "x-adapter-desativacao-terminal-cancel-terminal-requested-delay-error-exchange.q-adapter-desativacao-terminal-cancel-terminal-requested-error-retry", text: "x-adapter-desativacao-terminal-cancel-terminal-requested-delay-error-exchange.q-adapter-desativacao-terminal-cancel-terminal-requested-error-retry"},
                    {value: "x-adapter-gerencial-maintenance-buyer-approved.q-adapter-gerencial-buyer-approved-error-ack-reply", text: "x-adapter-gerencial-maintenance-buyer-approved.q-adapter-gerencial-buyer-approved-error-ack-reply"},
                    {value: "x-adapter-gerencial-maintenance-buyer-approved.q-adapter-gerencial-buyer-approved-error-retry", text: "x-adapter-gerencial-maintenance-buyer-approved.q-adapter-gerencial-buyer-approved-error-retry"},
                    {value: "x-adapter-gerencial-maintenance-fulfillment-internal-created.q-adapter-gerencial-error-ack-reply", text: "x-adapter-gerencial-maintenance-fulfillment-internal-created.q-adapter-gerencial-error-ack-reply"},
                    {value: "x-adapter-gerencial-maintenance-fulfillment-internal-created.q-adapter-gerencial-error-retry", text: "x-adapter-gerencial-maintenance-fulfillment-internal-created.q-adapter-gerencial-error-retry"},
                    {value: "x-adapter-gerencial-maintenance-merchant-approved.q-adapter-gerencial-merchant-approved-error-ack-reply", text: "x-adapter-gerencial-maintenance-merchant-approved.q-adapter-gerencial-merchant-approved-error-ack-reply"},
                    {value: "x-adapter-gerencial-maintenance-merchant-approved.q-adapter-gerencial-merchant-approved-error-retry", text: "x-adapter-gerencial-maintenance-merchant-approved.q-adapter-gerencial-merchant-approved-error-retry"},
                    {value: "x-adapter-plataforma-digital-delay-error-exchange.q-adapter-plataforma-digital-error-ack-reply", text: "x-adapter-plataforma-digital-delay-error-exchange.q-adapter-plataforma-digital-error-ack-reply"},
                    {value: "x-adapter-plataforma-digital-delay-error-exchange.q-adapter-plataforma-digital-error-retry", text: "x-adapter-plataforma-digital-delay-error-exchange.q-adapter-plataforma-digital-error-retry"},
                    {value: "x-adapter-sap-maintenance-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created-error-ack-reply", text: "x-adapter-sap-maintenance-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created-error-ack-reply"},
                    {value: "x-adapter-sap-maintenance-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created-error-retry", text: "x-adapter-sap-maintenance-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created-error-retry"},
                    {value: "x-adapter-sap-maintenance-order-cancel-requested.q-adapter-sap-order-cancel-requested-error-ack-reply", text: "x-adapter-sap-maintenance-order-cancel-requested.q-adapter-sap-order-cancel-requested-error-ack-reply"},
                    {value: "x-adapter-sap-maintenance-order-cancel-requested.q-adapter-sap-order-cancel-requested-error-retry", text: "x-adapter-sap-maintenance-order-cancel-requested.q-adapter-sap-order-cancel-requested-error-retry"},
                    {value: "x-adapter-sap-maintenance-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered-error-ack-reply", text: "x-adapter-sap-maintenance-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered-error-ack-reply"},
                    {value: "x-adapter-sap-maintenance-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered-error-retry", text: "x-adapter-sap-maintenance-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered-error-retry"},
                    {value: "x-adapter-sap-maintenance-order-payment-required.q-adapter-sap-order-payment-required-error-ack-reply", text: "x-adapter-sap-maintenance-order-payment-required.q-adapter-sap-order-payment-required-error-ack-reply"},
                    {value: "x-adapter-sap-maintenance-order-payment-required.q-adapter-sap-order-payment-required-error-reply", text: "x-adapter-sap-maintenance-order-payment-required.q-adapter-sap-order-payment-required-error-reply"},
                    {value: "x-adapter-sap-maintenance-order-rejected.q-adapter-sap-order-rejected-error-ack-reply", text: "x-adapter-sap-maintenance-order-rejected.q-adapter-sap-order-rejected-error-ack-reply"},
                    {value: "x-adapter-sap-maintenance-order-rejected.q-adapter-sap-order-rejected-error-retry", text: "x-adapter-sap-maintenance-order-rejected.q-adapter-sap-order-rejected-error-retry"},
                    {value: "x-adapter-sap-maintenance-order-submitted.q-adapter-sap-order-submitted-error-ack-reply", text: "x-adapter-sap-maintenance-order-submitted.q-adapter-sap-order-submitted-error-ack-reply"},
                    {value: "x-adapter-sap-maintenance-order-submitted.q-adapter-sap-order-submitted-error-reply", text: "x-adapter-sap-maintenance-order-submitted.q-adapter-sap-order-submitted-error-reply"},
                    {value: "x-adapter-siebel-maintenance-buyer-establishment-code-created.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-buyer-establishment-code-created.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-buyer-establishment-code-created.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-buyer-establishment-code-created.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-delivery-order-tracking-changed.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-delivery-order-tracking-changed.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-delivery-order-tracking-changed.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-delivery-order-tracking-changed.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-establishment-code-created.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-establishment-code-created.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-establishment-code-created.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-establishment-code-created.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-fulfillment-rent-created.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-fulfillment-rent-created.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-fulfillment-rent-created.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-fulfillment-rent-created.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-order-approved.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-order-approved.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-order-approved.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-order-approved.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-order-cancel-requested.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-order-cancel-requested.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-order-cancel-requested.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-order-cancel-requested.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-order-canceled.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-order-canceled.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-order-canceled.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-order-canceled.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-order-closed.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-order-closed.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-order-closed.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-order-closed.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-order-payment-required.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-order-payment-required.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-order-payment-required.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-order-payment-required.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-order-rejected.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-order-rejected.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-order-rejected.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-order-rejected.q-adapter-siebel-error-retry"},
                    {value: "x-adapter-siebel-maintenance-payment-transaction-processed.q-adapter-siebel-error-ack-reply", text: "x-adapter-siebel-maintenance-payment-transaction-processed.q-adapter-siebel-error-ack-reply"},
                    {value: "x-adapter-siebel-maintenance-payment-transaction-processed.q-adapter-siebel-error-retry", text: "x-adapter-siebel-maintenance-payment-transaction-processed.q-adapter-siebel-error-retry"},
                    {value: "x-agreement-merchant-pending-delay-error-exchange.q-agreement-merchant-pending-error-ack-reply", text: "x-agreement-merchant-pending-delay-error-exchange.q-agreement-merchant-pending-error-ack-reply"},
                    {value: "x-agreement-merchant-pending-delay-error-exchange.q-agreement-merchant-pending-error-retry", text: "x-agreement-merchant-pending-delay-error-exchange.q-agreement-merchant-pending-error-retry"},
                    {value: "x-agreement-qualification-merchant-pending-delay-error-exchange.q-agreement-qualification-merchant-pending-error-ack-reply", text: "x-agreement-qualification-merchant-pending-delay-error-exchange.q-agreement-qualification-merchant-pending-error-ack-reply"},
                    {value: "x-agreement.q-agreement", text: "x-agreement.q-agreement"},
                    {value: "x-agreement.q-agreement.dlq", text: "x-agreement.q-agreement.dlq"},
                    {value: "x-audit-change-stream-created.q-audit-agent-subscriber-audit-change-stream-created", text: "x-audit-change-stream-created.q-audit-agent-subscriber-audit-change-stream-created"},
                    {value: "x-audit-change-stream-created.q-audit-agent-subscriber-audit-change-stream-created.dlq", text: "x-audit-change-stream-created.q-audit-agent-subscriber-audit-change-stream-created.dlq"},
                    {value: "x-buyer-approved.q-adapter-gerencial-buyer-approved", text: "x-buyer-approved.q-adapter-gerencial-buyer-approved"},
                    {value: "x-buyer-approved.q-adapter-gerencial-buyer-approved.dlq", text: "x-buyer-approved.q-adapter-gerencial-buyer-approved.dlq"},
                    {value: "x-buyer-establishment-code-created.q-adapter-siebel-buyer-establishment-code-created", text: "x-buyer-establishment-code-created.q-adapter-siebel-buyer-establishment-code-created"},
                    {value: "x-buyer-establishment-code-created.q-adapter-siebel-buyer-establishment-code-created.dlq", text: "x-buyer-establishment-code-created.q-adapter-siebel-buyer-establishment-code-created.dlq"},
                    {value: "x-buyer-establishment-code-created.q-buyer-buyer-establishment-code-created", text: "x-buyer-establishment-code-created.q-buyer-buyer-establishment-code-created"},
                    {value: "x-buyer-establishment-code-created.q-buyer-buyer-establishment-code-created.dlq", text: "x-buyer-establishment-code-created.q-buyer-buyer-establishment-code-created.dlq"},
                    {value: "x-buyer-establishment-code-created.q-qualification-buyer-establishment-code-created", text: "x-buyer-establishment-code-created.q-qualification-buyer-establishment-code-created"},
                    {value: "x-buyer-establishment-code-created.q-qualification-buyer-establishment-code-created.dlq", text: "x-buyer-establishment-code-created.q-qualification-buyer-establishment-code-created.dlq"},
                    {value: "x-cancel-requested.q-cancel-cancel-requested", text: "x-cancel-requested.q-cancel-cancel-requested"},
                    {value: "", text: "x-cancel-resource-requested.q-adapter-desativacao-gerencial-cancel-resource-requested"},
                    {value: "x-cancel-resource-requested.q-adapter-desativacao-gerencial-cancel-resource-requested.dlq", text: "x-cancel-resource-requested.q-adapter-desativacao-gerencial-cancel-resource-requested.dlq"},
                    {value: "x-cancel-terminal-requested.q-adapter-desativacao-terminal-cancel-terminal-requested", text: "x-cancel-terminal-requested.q-adapter-desativacao-terminal-cancel-terminal-requested"},
                    {value: "x-cancel-terminal-requested.q-adapter-desativacao-terminal-cancel-terminal-requested.dlq", text: "x-cancel-terminal-requested.q-adapter-desativacao-terminal-cancel-terminal-requested.dlq"},
                    {value: "x-delivery-order-fulfillment-internal-created-delay-error-exchange.q-delivery-order-order-fulfillment-internal-created-error-retry", text: "x-delivery-order-fulfillment-internal-created-delay-error-exchange.q-delivery-order-order-fulfillment-internal-created-error-retry"},
                    {value: "x-delivery-order-fulfillment-item-product-processed-delay-error-exchange.q-delivery-order-order-fulfillment-item-product-processed-error-retry", text: "x-delivery-order-fulfillment-item-product-processed-delay-error-exchange.q-delivery-order-order-fulfillment-item-product-processed-error-retry"},
                    {value: "x-delivery-order-fulfillment-logical-terminal-created-delay-error-exchange.q-delivery-order-order-fulfillment-logical-terminal-created-error-retry", text: "x-delivery-order-fulfillment-logical-terminal-created-delay-error-exchange.q-delivery-order-order-fulfillment-logical-terminal-created-error-retry"},
                    {value: "x-delivery-order-fulfillment-processed-delay-error-exchange.q-delivery-order-order-fulfillment-processed-error-retry", text: "x-delivery-order-fulfillment-processed-delay-error-exchange.q-delivery-order-order-fulfillment-processed-error-retry"},
                    {value: "x-delivery-order-fulfillment-rent-created-delay-error-exchange.q-delivery-order-order-fulfillment-rent-created-error-retry", text: "x-delivery-order-fulfillment-rent-created-delay-error-exchange.q-delivery-order-order-fulfillment-rent-created-error-retry"},
                    {value: "x-delivery-order-fulfillment-sale-created-delay-error-exchange.q-delivery-order-order-fulfillment-sale-created-error-retry", text: "x-delivery-order-fulfillment-sale-created-delay-error-exchange.q-delivery-order-order-fulfillment-sale-created-error-retry"},
                    {value: "x-delivery-order-order-approved-delay-error-exchange.q-delivery-order--order-approved-error-retry", text: "x-delivery-order-order-approved-delay-error-exchange.q-delivery-order--order-approved-error-retry"},
                    {value: "x-delivery-order-order-payment-cancel-requested-delay-error-exchange.q-delivery-order--order-payment-cancel-requested-error-retry", text: "x-delivery-order-order-payment-cancel-requested-delay-error-exchange.q-delivery-order--order-payment-cancel-requested-error-retry"},
                    {value: "x-delivery-order-order-payment-registered-delay-error-exchange.q-delivery-order-order-payment-registered-error-retry", text: "x-delivery-order-order-payment-registered-delay-error-exchange.q-delivery-order-order-payment-registered-error-retry"},
                    {value: "x-delivery-order-order-payment-required-delay-error-exchange.q-delivery-order-order-payment-required-error-retry", text: "x-delivery-order-order-payment-required-delay-error-exchange.q-delivery-order-order-payment-required-error-retry"},
                    {value: "x-delivery-order-order-payment-unidentified-delay-error-exchange.q-delivery-order-order-payment-unidentified-error-retry", text: "x-delivery-order-order-payment-unidentified-delay-error-exchange.q-delivery-order-order-payment-unidentified-error-retry"},
                    {value: "x-delivery-order-order-qualified-delay-error-exchange.q-delivery-order-order-qualified-error-retry", text: "x-delivery-order-order-qualified-delay-error-exchange.q-delivery-order-order-qualified-error-retry"},
                    {value: "x-delivery-order-order-rejected-delay-error-exchange.q-delivery-order--order-rejected-error-retry", text: "x-delivery-order-order-rejected-delay-error-exchange.q-delivery-order--order-rejected-error-retry"},
                    {value: "x-delivery-order-order-submitted-delay-error-exchange.q-delivery-order-order-submitted-error-retry", text: "x-delivery-order-order-submitted-delay-error-exchange.q-delivery-order-order-submitted-error-retry"},
                    {value: "x-delivery-order-processed.q-delivery-order-marketplace-integration-processed", text: "x-delivery-order-processed.q-delivery-order-marketplace-integration-processed"},
                    {value: "x-delivery-order-processed.q-delivery-order-marketplace-integration-processed.dlq", text: "x-delivery-order-processed.q-delivery-order-marketplace-integration-processed.dlq"},
                    {value: "x-delivery-order-tracking-changed.q-adapter-siebel-delivery-order-tracking-changed", text: "x-delivery-order-tracking-changed.q-adapter-siebel-delivery-order-tracking-changed"},
                    {value: "x-delivery-order-tracking-changed.q-adapter-siebel-delivery-order-tracking-changed.dlq", text: "x-delivery-order-tracking-changed.q-adapter-siebel-delivery-order-tracking-changed.dlq"},
                    {value: "x-delivery-order-tracking-changed.q-marketplace-integration-tracking-changed", text: "x-delivery-order-tracking-changed.q-marketplace-integration-tracking-changed"},
                    {value: "x-delivery-order-tracking-changed.q-marketplace-integration-tracking-changed.dlq", text: "x-delivery-order-tracking-changed.q-marketplace-integration-tracking-changed.dlq"},
                    {value: "x-establishment-code-created-delay-error-exchange.q-qualification-establishment-code-created-delay-error-exchange", text: "x-establishment-code-created-delay-error-exchange.q-qualification-establishment-code-created-delay-error-exchange"},
                    {value: "x-establishment-code-created.q-adapter-integracao-establishment-code-created", text: "x-establishment-code-created.q-adapter-integracao-establishment-code-created"},
                    {value: "x-establishment-code-created.q-adapter-siebel-establishment-code-created", text: "x-establishment-code-created.q-adapter-siebel-establishment-code-created"},
                    {value: "x-establishment-code-created.q-adapter-siebel-establishment-code-created.dlq", text: "x-establishment-code-created.q-adapter-siebel-establishment-code-created.dlq"},
                    {value: "x-establishment-code-created.q-merchant-establishment-code-created", text: "x-establishment-code-created.q-merchant-establishment-code-created"},
                    {value: "x-establishment-code-created.q-merchant-establishment-code-created.dlq", text: "x-establishment-code-created.q-merchant-establishment-code-created.dlq"},
                    {value: "x-establishment-code-created.q-qualification-establishment-code-created", text: "x-establishment-code-created.q-qualification-establishment-code-created"},
                    {value: "x-establishment-code-created.q-qualification-establishment-code-created.dlq", text: "x-establishment-code-created.q-qualification-establishment-code-created.dlq"},
                    {value: "x-fulfillment-internal-created.q-adapter-gerencial-fulfillment-internal-created", text: "x-fulfillment-internal-created.q-adapter-gerencial-fulfillment-internal-created"},
                    {value: "x-fulfillment-internal-created.q-adapter-gerencial-fulfillment-internal-created.dlq", text: "x-fulfillment-internal-created.q-adapter-gerencial-fulfillment-internal-created.dlq"},
                    {value: "x-fulfillment-internal-created.q-adapter-plataforma-digital-fulfillment-internal-created", text: "x-fulfillment-internal-created.q-adapter-plataforma-digital-fulfillment-internal-created"},
                    {value: "x-fulfillment-internal-created.q-adapter-plataforma-digital-fulfillment-internal-created.dlq", text: "x-fulfillment-internal-created.q-adapter-plataforma-digital-fulfillment-internal-created.dlq"},
                    {value: "x-fulfillment-internal-created.q-delivery-order-fulfillment-internal-created", text: "x-fulfillment-internal-created.q-delivery-order-fulfillment-internal-created"},
                    {value: "x-fulfillment-internal-created.q-delivery-order-fulfillment-internal-created.dlq", text: "x-fulfillment-internal-created.q-delivery-order-fulfillment-internal-created.dlq"},
                    {value: "x-fulfillment-internal-created.q-order-fulfillment-internal-created", text: "x-fulfillment-internal-created.q-order-fulfillment-internal-created"},
                    {value: "x-fulfillment-internal-created.q-order-fulfillment-internal-created.dlq", text: "x-fulfillment-internal-created.q-order-fulfillment-internal-created.dlq"},
                    {value: "x-fulfillment-internal-fulfillment-internal-processed-delay-error-exchange.q-fulfillment-internal-fulfillment-internal-processed-error-ack-reply", text: "x-fulfillment-internal-fulfillment-internal-processed-delay-error-exchange.q-fulfillment-internal-fulfillment-internal-processed-error-ack-reply"},
                    {value: "x-fulfillment-internal-fulfillment-internal-processed-delay-error-exchange.q-fulfillment-internal-fulfillment-internal-processed-error-retry", text: "x-fulfillment-internal-fulfillment-internal-processed-delay-error-exchange.q-fulfillment-internal-fulfillment-internal-processed-error-retry"},
                    {value: "x-fulfillment-internal-order-approved-delay-error-exchange.q-fulfillment-internal-order-approved-error-ack-reply", text: "x-fulfillment-internal-order-approved-delay-error-exchange.q-fulfillment-internal-order-approved-error-ack-reply"},
                    {value: "x-fulfillment-internal-order-approved-delay-error-exchange.q-fulfillment-internal-order-approved-error-retry", text: "x-fulfillment-internal-order-approved-delay-error-exchange.q-fulfillment-internal-order-approved-error-retry"},
                    {value: "x-fulfillment-internal-processed.q-fulfillment-internal-fulfillment-internal-processed", text: "x-fulfillment-internal-processed.q-fulfillment-internal-fulfillment-internal-processed"},
                    {value: "x-fulfillment-internal-processed.q-fulfillment-internal-fulfillment-internal-processed.dlq", text: "x-fulfillment-internal-processed.q-fulfillment-internal-fulfillment-internal-processed.dlq"},
                    {value: "x-fulfillment-item-product-processed.q-delivery-order-fulfillment-item-product-processed", text: "x-fulfillment-item-product-processed.q-delivery-order-fulfillment-item-product-processed"},
                    {value: "x-fulfillment-item-product-processed.q-delivery-order-fulfillment-item-product-processed.dlq", text: "x-fulfillment-item-product-processed.q-delivery-order-fulfillment-item-product-processed.dlq"},
                    {value: "x-fulfillment-logical-terminal-created.q-adapter-ativacao-terminal-fulfillment-logical-terminal-created", text: "x-fulfillment-logical-terminal-created.q-adapter-ativacao-terminal-fulfillment-logical-terminal-created"},
                    {value: "x-fulfillment-logical-terminal-created.q-adapter-ativacao-terminal-fulfillment-logical-terminal-created.dlq", text: "x-fulfillment-logical-terminal-created.q-adapter-ativacao-terminal-fulfillment-logical-terminal-created.dlq"},
                    {value: "x-fulfillment-logical-terminal-created.q-delivery-order-fulfillment-logical-terminal-created", text: "x-fulfillment-logical-terminal-created.q-delivery-order-fulfillment-logical-terminal-created"},
                    {value: "x-fulfillment-logical-terminal-created.q-delivery-order-fulfillment-logical-terminal-created.dlq", text: "x-fulfillment-logical-terminal-created.q-delivery-order-fulfillment-logical-terminal-created.dlq"},
                    {value: "x-fulfillment-logical-terminal-created.q-order-fulfillment-logical-terminal-created", text: "x-fulfillment-logical-terminal-created.q-order-fulfillment-logical-terminal-created"},
                    {value: "x-fulfillment-logical-terminal-created.q-order-fulfillment-logical-terminal-created.dlq", text: "x-fulfillment-logical-terminal-created.q-order-fulfillment-logical-terminal-created.dlq"},
                    {value: "x-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-delay-error-exchange.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-error-ack-reply", text: "x-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-delay-error-exchange.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-error-ack-reply"},
                    {value: "x-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-delay-error-exchange.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-error-retry", text: "x-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-delay-error-exchange.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed-error-retry"},
                    {value: "x-fulfillment-logical-terminal-order-approved-delay-error-exchange.q-fulfillment-logical-terminal-order-approved-error-ack-reply", text: "x-fulfillment-logical-terminal-order-approved-delay-error-exchange.q-fulfillment-logical-terminal-order-approved-error-ack-reply"},
                    {value: "x-fulfillment-logical-terminal-order-approved-delay-error-exchange.q-fulfillment-logical-terminal-order-approved-error-retry", text: "x-fulfillment-logical-terminal-order-approved-delay-error-exchange.q-fulfillment-logical-terminal-order-approved-error-retry"},
                    {value: "x-fulfillment-logical-terminal-processed.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed", text: "x-fulfillment-logical-terminal-processed.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed"},
                    {value: "x-fulfillment-logical-terminal-processed.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed.dlq", text: "x-fulfillment-logical-terminal-processed.q-fulfillment-logical-terminal-fulfillment-logical-terminal-processed.dlq"},
                    {value: "x-fulfillment-processed.q-delivery-order-fulfillment-processed.dlq", text: "x-fulfillment-processed.q-delivery-order-fulfillment-processed.dlq"},
                    {value: "x-fulfillment-rent-created.q-adapter-siebel-fulfillment-rent-created", text: "x-fulfillment-rent-created.q-adapter-siebel-fulfillment-rent-created"},
                    {value: "x-fulfillment-rent-created.q-adapter-siebel-fulfillment-rent-created.dlq", text: "x-fulfillment-rent-created.q-adapter-siebel-fulfillment-rent-created.dlq"},
                    {value: "x-fulfillment-rent-created.q-delivery-order-fulfillment-rent-created", text: "x-fulfillment-rent-created.q-delivery-order-fulfillment-rent-created"},
                    {value: "x-fulfillment-rent-created.q-delivery-order-fulfillment-rent-created.dlq", text: "x-fulfillment-rent-created.q-delivery-order-fulfillment-rent-created.dlq"},
                    {value: "x-fulfillment-rent-created.q-order-fulfillment-rent-created", text: "x-fulfillment-rent-created.q-order-fulfillment-rent-created"},
                    {value: "x-fulfillment-rent-created.q-order-fulfillment-rent-created.dlq", text: "x-fulfillment-rent-created.q-order-fulfillment-rent-created.dlq"},
                    {value: "x-fulfillment-rent-maintenance-fulfillment-rent-processed.q-fulfillment-rent-maintenance-fulfillment-rent-processed-error-ack-reply", text: "x-fulfillment-rent-maintenance-fulfillment-rent-processed.q-fulfillment-rent-maintenance-fulfillment-rent-processed-error-ack-reply"},
                    {value: "x-fulfillment-rent-maintenance-fulfillment-rent-processed.q-fulfillment-rent-maintenance-fulfillment-rent-processed-error-retry", text: "x-fulfillment-rent-maintenance-fulfillment-rent-processed.q-fulfillment-rent-maintenance-fulfillment-rent-processed-error-retry"},
                    {value: "x-fulfillment-rent-maintenance-order-approved.q-fulfillment-rent-maintenance-order-approved-error-ack-reply", text: "x-fulfillment-rent-maintenance-order-approved.q-fulfillment-rent-maintenance-order-approved-error-ack-reply"},
                    {value: "x-fulfillment-rent-maintenance-order-approved.q-fulfillment-rent-maintenance-order-approved-error-retry", text: "x-fulfillment-rent-maintenance-order-approved.q-fulfillment-rent-maintenance-order-approved-error-retry"},
                    {value: "x-fulfillment-rent-processed.q-fulfillment-rent-fulfillment-rent-processed", text: "x-fulfillment-rent-processed.q-fulfillment-rent-fulfillment-rent-processed"},
                    {value: "x-fulfillment-rent-processed.q-fulfillment-rent-fulfillment-rent-processed.dlq", text: "x-fulfillment-rent-processed.q-fulfillment-rent-fulfillment-rent-processed.dlq"},
                    {value: "x-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created", text: "x-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created"},
                    {value: "x-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created.dlq", text: "x-fulfillment-sale-created.q-adapter-sap-fulfillment-sale-created.dlq"},
                    {value: "x-fulfillment-sale-created.q-delivery-order-fulfillment-sale-created", text: "x-fulfillment-sale-created.q-delivery-order-fulfillment-sale-created"},
                    {value: "x-fulfillment-sale-created.q-delivery-order-fulfillment-sale-created.dlq", text: "x-fulfillment-sale-created.q-delivery-order-fulfillment-sale-created.dlq"},
                    {value: "x-fulfillment-sale-created.q-order-fulfillment-sale-created", text: "x-fulfillment-sale-created.q-order-fulfillment-sale-created"},
                    {value: "x-fulfillment-sale-created.q-order-fulfillment-sale-created.dlq", text: "x-fulfillment-sale-created.q-order-fulfillment-sale-created.dlq"},
                    {value: "x-fulfillment-sale-fulfillment-sale-processed-delay-error-exchange.q-fulfillment-sale-fulfillment-sale-processed-error-ack-reply", text: "x-fulfillment-sale-fulfillment-sale-processed-delay-error-exchange.q-fulfillment-sale-fulfillment-sale-processed-error-ack-reply"},
                    {value: "x-fulfillment-sale-fulfillment-sale-processed-delay-error-exchange.q-fulfillment-sale-fulfillment-sale-processed-error-retry", text: "x-fulfillment-sale-fulfillment-sale-processed-delay-error-exchange.q-fulfillment-sale-fulfillment-sale-processed-error-retry"},
                    {value: "x-fulfillment-sale-order-approved-delay-error-exchange.q-fulfillment-sale-order-approved-error-ack-reply", text: "x-fulfillment-sale-order-approved-delay-error-exchange.q-fulfillment-sale-order-approved-error-ack-reply"},
                    {value: "x-fulfillment-sale-order-approved-delay-error-exchange.q-fulfillment-sale-order-approved-error-retry", text: "x-fulfillment-sale-order-approved-delay-error-exchange.q-fulfillment-sale-order-approved-error-retry"},
                    {value: "x-fulfillment-sale-processed.q-fulfillment-sale-fulfillment-sale-processed", text: "x-fulfillment-sale-processed.q-fulfillment-sale-fulfillment-sale-processed"},
                    {value: "x-fulfillment-sale-processed.q-fulfillment-sale-fulfillment-sale-processed.dlq", text: "x-fulfillment-sale-processed.q-fulfillment-sale-fulfillment-sale-processed.dlq"},
                    {value: "x-maintenance-error-events.q-maintenance-error-events", text: "x-maintenance-error-events.q-maintenance-error-events"},
                    {value: "x-marketplace-integration-maintenance-canceled.q-marketplace-integration-canceled-error-ack-reply", text: "x-marketplace-integration-maintenance-canceled.q-marketplace-integration-canceled-error-ack-reply"},
                    {value: "x-marketplace-integration-maintenance-processed.q-marketplace-integration-processed-error-ack-reply", text: "x-marketplace-integration-maintenance-processed.q-marketplace-integration-processed-error-ack-reply"},
                    {value: "x-marketplace-integration-tracking-changed.q-marketplace-integration-processed-error-ack-reply", text: "x-marketplace-integration-tracking-changed.q-marketplace-integration-processed-error-ack-reply"},
                    {value: "x-merchant-approved.q-adapter-gerencial-merchant-approved", text: "x-merchant-approved.q-adapter-gerencial-merchant-approved"},
                    {value: "x-merchant-approved.q-adapter-gerencial-merchant-approved.dlq", text: "x-merchant-approved.q-adapter-gerencial-merchant-approved.dlq"},
                    {value: "x-merchant-approved.q-adapter-integracao-merchant-approved", text: "x-merchant-approved.q-adapter-integracao-merchant-approved"},
                    {value: "x-merchant-approved.q-qualification-merchant-approved", text: "x-merchant-approved.q-qualification-merchant-approved"},
                    {value: "x-merchant-delay-error-exchange.q-merchant-error-ack-reply", text: "x-merchant-delay-error-exchange.q-merchant-error-ack-reply"},
                    {value: "x-merchant-delay-error-exchange.q-merchant-error-retry", text: "x-merchant-delay-error-exchange.q-merchant-error-retry"},
                    {value: "x-merchant-pending.q-merchant-pending.dlq", text: "x-merchant-pending.q-merchant-pending.dlq"},
                    {value: "x-merchant-qualified-delay-error-exchange.q-qualification-merchant-qualified-ack-reply", text: "x-merchant-qualified-delay-error-exchange.q-qualification-merchant-qualified-ack-reply"},
                    {value: "x-merchant-qualified-delay-error-exchange.q-qualification-merchant-qualified-error-retry", text: "x-merchant-qualified-delay-error-exchange.q-qualification-merchant-qualified-error-retry"},
                    {value: "x-merchant-qualified.q-qualification-merchant-qualified", text: "x-merchant-qualified.q-qualification-merchant-qualified"},
                    {value: "x-merchant-qualified.q-qualification-merchant-qualified.dlq", text: "x-merchant-qualified.q-qualification-merchant-qualified.dlq"},
                    {value: "x-merchant-rejected.q-qualification-merchant-rejected", text: "x-merchant-rejected.q-qualification-merchant-rejected"},
                    {value: "x-merchant-reproved.q-qualification-merchant-reproved", text: "x-merchant-reproved.q-qualification-merchant-reproved"},
                    {value: "x-merchant-submitted.q-qualification-merchant-submitted", text: "x-merchant-submitted.q-qualification-merchant-submitted"},
                    {value: "x-order-approved.q-adapter-siebel-order-approved", text: "x-order-approved.q-adapter-siebel-order-approved"},
                    {value: "x-order-approved.q-adapter-siebel-order-approved.dlq", text: "x-order-approved.q-adapter-siebel-order-approved.dlq"},
                    {value: "x-order-approved.q-delivery-order-order-approved", text: "x-order-approved.q-delivery-order-order-approved"},
                    {value: "x-order-approved.q-delivery-order-order-approved.dlq", text: "x-order-approved.q-delivery-order-order-approved.dlq"},
                    {value: "x-order-approved.q-fulfillment-internal-order-approved", text: "x-order-approved.q-fulfillment-internal-order-approved"},
                    {value: "x-order-approved.q-fulfillment-internal-order-approved.dlq", text: "x-order-approved.q-fulfillment-internal-order-approved.dlq"},
                    {value: "x-order-approved.q-fulfillment-logical-terminal-order-approved", text: "x-order-approved.q-fulfillment-logical-terminal-order-approved"},
                    {value: "x-order-approved.q-fulfillment-logical-terminal-order-approved.dlq", text: "x-order-approved.q-fulfillment-logical-terminal-order-approved.dlq"},
                    {value: "x-order-approved.q-fulfillment-rent-order-approved", text: "x-order-approved.q-fulfillment-rent-order-approved"},
                    {value: "x-order-approved.q-fulfillment-rent-order-approved.dlq", text: "x-order-approved.q-fulfillment-rent-order-approved.dlq"},
                    {value: "x-order-approved.q-fulfillment-sale-order-approved", text: "x-order-approved.q-fulfillment-sale-order-approved"},
                    {value: "x-order-approved.q-fulfillment-sale-order-approved.dlq", text: "x-order-approved.q-fulfillment-sale-order-approved.dlq"},
                    {value: "x-order-cancel-requested.q-adapter-sap-order-cancel-requested", text: "x-order-cancel-requested.q-adapter-sap-order-cancel-requested"},
                    {value: "x-order-cancel-requested.q-adapter-sap-order-cancel-requested.dlq", text: "x-order-cancel-requested.q-adapter-sap-order-cancel-requested.dlq"},
                    {value: "x-order-cancel-requested.q-adapter-siebel-order-cancel-requested", text: "x-order-cancel-requested.q-adapter-siebel-order-cancel-requested"},
                    {value: "x-order-cancel-requested.q-adapter-siebel-order-cancel-requested.dlq", text: "x-order-cancel-requested.q-adapter-siebel-order-cancel-requested.dlq"},
                    {value: "x-order-canceled.q-adapter-siebel-order-canceled", text: "x-order-canceled.q-adapter-siebel-order-canceled"},
                    {value: "x-order-canceled.q-adapter-siebel-order-canceled.dlq", text: "x-order-canceled.q-adapter-siebel-order-canceled.dlq"},
                    {value: "x-order-canceled.q-delivery-order-order-canceled", text: "x-order-canceled.q-delivery-order-order-canceled"},
                    {value: "x-order-canceled.q-delivery-order-order-canceled.dlq", text: "x-order-canceled.q-delivery-order-order-canceled.dlq"},
                    {value: "x-order-canceled.q-marketplace-integration-canceled", text: "x-order-canceled.q-marketplace-integration-canceled"},
                    {value: "x-order-canceled.q-marketplace-integration-canceled.dlq", text: "x-order-canceled.q-marketplace-integration-canceled.dlq"},
                    {value: "x-order-canceled.q-receivables-order-canceled", text: "x-order-canceled.q-receivables-order-canceled"},
                    {value: "x-order-canceled.q-receivables-order-canceled.dlq", text: "x-order-canceled.q-receivables-order-canceled.dlq"},
                    {value: "x-order-cancelment-allowed-delay-error-exchange.q-order-cancelment-allowed-error-retry", text: "x-order-cancelment-allowed-delay-error-exchange.q-order-cancelment-allowed-error-retry"},
                    {value: "x-order-cancelment-allowed.q-order-cancelment-allowed", text: "x-order-cancelment-allowed.q-order-cancelment-allowed"},
                    {value: "x-order-cancelment-allowed.q-order-cancelment-allowed.dlq", text: "x-order-cancelment-allowed.q-order-cancelment-allowed.dlq"},
                    {value: "x-order-closed.q-adapter-siebel-order-closed", text: "x-order-closed.q-adapter-siebel-order-closed"},
                    {value: "x-order-closed.q-adapter-siebel-order-closed.dlq", text: "x-order-closed.q-adapter-siebel-order-closed.dlq"},
                    {value: "x-order-item-changed-delay-error-exchange.q-order-order-item-changed-error-retry", text: "x-order-item-changed-delay-error-exchange.q-order-order-item-changed-error-retry"},
                    {value: "x-order-item-changed.q-order-order-item-changed", text: "x-order-item-changed.q-order-order-item-changed"},
                    {value: "x-order-item-changed.q-order-order-item-changed.dlq", text: "x-order-item-changed.q-order-order-item-changed.dlq"},
                    {value: "x-order-items-canceled.q-receivables-order-items-canceled", text: "x-order-items-canceled.q-receivables-order-items-canceled"},
                    {value: "x-order-items-canceled.q-receivables-order-items-canceled.dlq", text: "x-order-items-canceled.q-receivables-order-items-canceled.dlq"},
                    {value: "x-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered", text: "x-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered"},
                    {value: "x-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered.dlq", text: "x-order-payment-cancel-registered.q-adapter-sap-order-payment-cancel-registered.dlq"},
                    {value: "x-order-payment-cancel-requested.q-delivery-order-order-payment-cancel-requested", text: "x-order-payment-cancel-requested.q-delivery-order-order-payment-cancel-requested"},
                    {value: "x-order-payment-cancel-requested.q-delivery-order-order-payment-cancel-requested.dlq", text: "x-order-payment-cancel-requested.q-delivery-order-order-payment-cancel-requested.dlq"},
                    {value: "x-order-payment-pending.q-adapter-siebel-order-payment-pending", text: "x-order-payment-pending.q-adapter-siebel-order-payment-pending"},
                    {value: "x-order-payment-pending.q-adapter-siebel-order-payment-pending.dlq", text: "x-order-payment-pending.q-adapter-siebel-order-payment-pending.dlq"},
                    {value: "x-order-payment-registered-delay-error-exchange.q-order-payment-registered-error-retry", text: "x-order-payment-registered-delay-error-exchange.q-order-payment-registered-error-retry"},
                    {value: "x-order-payment-registered.q-delivery-order-order-payment-registered", text: "x-order-payment-registered.q-delivery-order-order-payment-registered"},
                    {value: "x-order-payment-registered.q-delivery-order-order-payment-registered.dlq", text: "x-order-payment-registered.q-delivery-order-order-payment-registered.dlq"},
                    {value: "x-order-payment-registered.q-order-order-payment-registered", text: "x-order-payment-registered.q-order-order-payment-registered"},
                    {value: "x-order-payment-registered.q-order-order-payment-registered.dlq", text: "x-order-payment-registered.q-order-order-payment-registered.dlq"},
                    {value: "x-order-payment-required.q-adapter-sap-order-payment-required", text: "x-order-payment-required.q-adapter-sap-order-payment-required"},
                    {value: "x-order-payment-required.q-adapter-sap-order-payment-required.dlq", text: "x-order-payment-required.q-adapter-sap-order-payment-required.dlq"},
                    {value: "x-order-payment-required.q-adapter-siebel-order-payment-required", text: "x-order-payment-required.q-adapter-siebel-order-payment-required"},
                    {value: "x-order-payment-required.q-adapter-siebel-order-payment-required.dlq", text: "x-order-payment-required.q-adapter-siebel-order-payment-required.dlq"},
                    {value: "x-order-payment-required.q-delivery-order-order-payment-required", text: "x-order-payment-required.q-delivery-order-order-payment-required"},
                    {value: "x-order-payment-required.q-delivery-order-order-payment-required.dlq", text: "x-order-payment-required.q-delivery-order-order-payment-required.dlq"},
                    {value: "x-order-payment-required.q-receivables-order-payment-required", text: "x-order-payment-required.q-receivables-order-payment-required"},
                    {value: "x-order-payment-required.q-receivables-order-payment-required.dlq", text: "x-order-payment-required.q-receivables-order-payment-required.dlq"},
                    {value: "x-order-payment-unidentified-delay-error-exchange.q-order-payment-unidentified-error-retry", text: "x-order-payment-unidentified-delay-error-exchange.q-order-payment-unidentified-error-retry"},
                    {value: "x-order-qualified-delay-error-exchange.q-order-order-qualified-error-retry", text: "x-order-qualified-delay-error-exchange.q-order-order-qualified-error-retry"},
                    {value: "x-order-qualified.q-delivery-order-order-qualified", text: "x-order-qualified.q-delivery-order-order-qualified"},
                    {value: "x-order-qualified.q-delivery-order-order-qualified.dlq", text: "x-order-qualified.q-delivery-order-order-qualified.dlq"},
                    {value: "x-order-qualified.q-order-order-qualified", text: "x-order-qualified.q-order-order-qualified"},
                    {value: "x-order-rejected.q-adapter-sap-order-rejected", text: "x-order-rejected.q-adapter-sap-order-rejected"},
                    {value: "x-order-rejected.q-adapter-sap-order-rejected.dlq", text: "x-order-rejected.q-adapter-sap-order-rejected.dlq"},
                    {value: "x-order-rejected.q-adapter-siebel-order-rejected", text: "x-order-rejected.q-adapter-siebel-order-rejected"},
                    {value: "x-order-rejected.q-adapter-siebel-order-rejected.dlq", text: "x-order-rejected.q-adapter-siebel-order-rejected.dlq"},
                    {value: "x-order-rejected.q-delivery-order-order-rejected", text: "x-order-rejected.q-delivery-order-order-rejected"},
                    {value: "x-order-rejected.q-delivery-order-order-rejected.dlq", text: "x-order-rejected.q-delivery-order-order-rejected.dlq"},
                    {value: "x-order-rejected.q-receivables-order-rejected", text: "x-order-rejected.q-receivables-order-rejected"},
                    {value: "x-order-rejected.q-receivables-order-rejected.dlq", text: "x-order-rejected.q-receivables-order-rejected.dlq"},
                    {value: "x-order-submitted.q-adapter-sap-order-submitted", text: "x-order-submitted.q-adapter-sap-order-submitted"},
                    {value: "x-order-submitted.q-delivery-order-order-submitted", text: "x-order-submitted.q-delivery-order-order-submitted"},
                    {value: "x-order-submitted.q-delivery-order-order-submitted.dlq", text: "x-order-submitted.q-delivery-order-order-submitted.dlq"},
                    {value: "x-order-submitted.q-qualification-order-submitted", text: "x-order-submitted.q-qualification-order-submitted"},
                    {value: "x-order-submitted.q-qualification-order-submitted.dlq", text: "x-order-submitted.q-qualification-order-submitted.dlq"},
                    {value: "x-payment-transaction-processed.q-adapter-siebel-payment-transaction-processed", text: "x-payment-transaction-processed.q-adapter-siebel-payment-transaction-processed"},
                    {value: "x-payment-transaction-processed.q-adapter-siebel-payment-transaction-processed.dlq", text: "x-payment-transaction-processed.q-adapter-siebel-payment-transaction-processed.dlq"},
                    {value: "x-payment-transaction-processed.q-delivery-order-payment-transaction-processed", text: "x-payment-transaction-processed.q-delivery-order-payment-transaction-processed"},
                    {value: "x-payment-transaction-processed.q-delivery-order-payment-transaction-processed.dlq", text: "x-payment-transaction-processed.q-delivery-order-payment-transaction-processed.dlq"},
                    {value: "x-payment-unidentified.q-delivery-order-payment-unidentified", text: "x-payment-unidentified.q-delivery-order-payment-unidentified"},
                    {value: "x-payment-unidentified.q-delivery-order-payment-unidentified.dlq", text: "x-payment-unidentified.q-delivery-order-payment-unidentified.dlq"},
                    {value: "x-payment-unidentified.q-order-payment-unidentified", text: "x-payment-unidentified.q-order-payment-unidentified"},
                    {value: "x-payment-unidentified.q-order-payment-unidentified.dlq", text: "x-payment-unidentified.q-order-payment-unidentified.dlq"},
                    {value: "x-qualification-buyer-establishment-code-created-delay-error-exchange.q-qualification-buyer-establishment-code-error-retry", text: "x-qualification-buyer-establishment-code-created-delay-error-exchange.q-qualification-buyer-establishment-code-error-retry"},
                    {value: "x-qualification-merchant-pending.q-qualification-merchant-pending", text: "x-qualification-merchant-pending.q-qualification-merchant-pending"},
                    {value: "x-qualification-merchant-pending.q-qualification-merchant-pending.dlq", text: "x-qualification-merchant-pending.q-qualification-merchant-pending.dlq"},
                    {value: "x-qualification-order-submitted-delay-error-exchange.q-qualification-order-submitted-error-retry", text: "x-qualification-order-submitted-delay-error-exchange.q-qualification-order-submitted-error-retry"},
                    {value: "x-receivables-maintenance-order-canceled.q-receivables-order-canceled-error-ack-reply", text: "x-receivables-maintenance-order-canceled.q-receivables-order-canceled-error-ack-reply"},
                    {value: "x-receivables-maintenance-order-canceled.q-receivables-order-canceled-error-retry", text: "x-receivables-maintenance-order-canceled.q-receivables-order-canceled-error-retry"},
                    {value: "x-receivables-maintenance-order-items-canceled.q-receivables-order-items-canceled-error-ack-reply", text: "x-receivables-maintenance-order-items-canceled.q-receivables-order-items-canceled-error-ack-reply"},
                    {value: "x-receivables-maintenance-order-items-canceled.q-receivables-order-items-canceled-error-retry", text: "x-receivables-maintenance-order-items-canceled.q-receivables-order-items-canceled-error-retry"},
                    {value: "x-receivables-maintenance-order-payment-required.q-receivables-order-payment-required-error-ack-reply", text: "x-receivables-maintenance-order-payment-required.q-receivables-order-payment-required-error-ack-reply"},
                    {value: "x-receivables-maintenance-order-payment-required.q-receivables-order-payment-required-error-retry", text: "x-receivables-maintenance-order-payment-required.q-receivables-order-payment-required-error-retry"},
                    {value: "x-receivables-maintenance-order-rejected.q-receivables-order-rejected-error-ack-reply", text: "x-receivables-maintenance-order-rejected.q-receivables-order-rejected-error-ack-reply"},
                    {value: "x-receivables-maintenance-order-rejected.q-receivables-order-rejected-error-retry", text: "x-receivables-maintenance-order-rejected.q-receivables-order-rejected-error-retry"},
                    {value: "x-resource-canceled.q-cancel-resource-canceled", text: "x-resource-canceled.q-cancel-resource-canceled"},
                    {value: "x-terminal-canceled.q-cancel-terminal-canceled", text: "x-terminal-canceled.q-cancel-terminal-canceled"}
                ]
            },
            traceId: {
                label: 'traceID',
                name: 'traceId',
                type: 'text',
                placeholder: ''
            }
        }

        return(
            <form className="row search-form form-inline" onSubmit={(event) => handleSubmit(event, formData.values)}>
                <div className="col-12">
                    <h4 className="color-red"><i className="fa fa-search"></i> Filtros</h4>
                </div>
                <div className="col-12">
                    <Field { ...formConfig.originalMessage } component={InlineField} />
                </div>
                <div className="col-12">
                    <Field { ...formConfig.error } component={InlineField} />
                </div>              
                <div className="col-12">
                    <Field { ...formConfig.traceId } component={InlineField} />
                </div>
                <div className="col-12">
                    <Field { ...formConfig.statusReprocess } component={InlineField} />
                </div>
                <div className="col-12">
                    <Field { ...formConfig.errorDate } component={DateTime} />
                </div>
                <div className="col-12">
                    <Field { ...formConfig.serviceName } component={InlineField} />
                </div>
                <div className="col-12">
                    <Field { ...formConfig.originalExchange } component={InlineField} />
                </div>
                <div className="col-12">
                    <Field { ...formConfig.originalQueue } component={InlineField} />
                </div>

                <div className="col-12 mt-5 text-right">
                    <Button classList="btn-lg btn-grey inverse" icon="icon icon-exclude" onClick={() => this.props.reset('searchForm')}>limpar</Button>
                    <Button type="submit" classList="btn-lg btn-red inverse ml-5" icon="icon icon-search">buscar</Button>
                </div>
            </form>
        )   
    }
}

SearchForm = reduxForm({
    form: 'searchForm',
    enableReinitialize: true,
    destroyOnUnmount: false
})(SearchForm)

const mapStateToProps = (store) => {
    return {
        formData: store.form.searchForm,
    }
}

export default connect(mapStateToProps)(SearchForm)