import React, { Component } from 'react';
import {Route} from 'react-router-dom';
import Login from './components/User/Login';
import Register from './components/User/Register';
import Menu from './components/Menu';
import ListTechniques from './components/Techniques/Index';
import AddTechniques from './components/Techniques/Add';
//import * as TechniquesAPI from './utils/TechniquesAPI';

class App extends Component {

  state = {    
    techniques : [
      {
          "id": 4,
          "name": "Trinity O'Connell",
          "difficulty": 9,
          "effect": 0,
          "form": "3",
          "area": 0,
          "duration": 3,
          "execution": 6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 5,
          "name": "Jacklyn Dibbert",
          "difficulty": 24,
          "effect": 6,
          "form": "3",
          "area": 3,
          "duration": 6,
          "execution": 6,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 6,
          "name": "Modesto Howell",
          "difficulty": 9,
          "effect": 0,
          "form": "0",
          "area": 6,
          "duration": 3,
          "execution": 3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 7,
          "name": "Jarrod Kuhlman",
          "difficulty": 12,
          "effect": 0,
          "form": "6",
          "area": 0,
          "duration": 6,
          "execution": 3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 8,
          "name": "Mervin Krajcik",
          "difficulty": 18,
          "effect": 12,
          "form": "0",
          "area": 3,
          "duration": 6,
          "execution": -3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 9,
          "name": "Berniece Kovacek IV",
          "difficulty": 9,
          "effect": 6,
          "form": "3",
          "area": 0,
          "duration": 3,
          "execution": 0,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 10,
          "name": "Franco Smith PhD",
          "difficulty": 9,
          "effect": 9,
          "form": "0",
          "area": 3,
          "duration": 3,
          "execution": -3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 11,
          "name": "Alexandra Schmidt",
          "difficulty": 18,
          "effect": 3,
          "form": "6",
          "area": 3,
          "duration": 6,
          "execution": 3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 12,
          "name": "Prof. Newton Daniel V",
          "difficulty": 33,
          "effect": 15,
          "form": "6",
          "area": 6,
          "duration": 3,
          "execution": 3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 13,
          "name": "Juston Thompson",
          "difficulty": 15,
          "effect": 0,
          "form": "6",
          "area": 6,
          "duration": 0,
          "execution": 6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 14,
          "name": "Nora Torphy",
          "difficulty": 6,
          "effect": 3,
          "form": "6",
          "area": 0,
          "duration": 3,
          "execution": 0,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 15,
          "name": "Veda Kunze",
          "difficulty": 12,
          "effect": 3,
          "form": "6",
          "area": 6,
          "duration": 0,
          "execution": 3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 16,
          "name": "Ms. Lorna Stehr",
          "difficulty": 3,
          "effect": 12,
          "form": "0",
          "area": 0,
          "duration": 0,
          "execution": -6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 17,
          "name": "Keshawn Stracke",
          "difficulty": 30,
          "effect": 15,
          "form": "6",
          "area": 3,
          "duration": 0,
          "execution": 6,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 18,
          "name": "Kaden Effertz Jr.",
          "difficulty": 9,
          "effect": 3,
          "form": "0",
          "area": 6,
          "duration": 0,
          "execution": 3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 19,
          "name": "Prof. Javier Sauer Jr.",
          "difficulty": 18,
          "effect": 3,
          "form": "3",
          "area": 3,
          "duration": 6,
          "execution": 3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 20,
          "name": "Peter Rohan",
          "difficulty": 12,
          "effect": 12,
          "form": "0",
          "area": 3,
          "duration": 0,
          "execution": -3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 21,
          "name": "Ebba Quigley",
          "difficulty": 6,
          "effect": 6,
          "form": "3",
          "area": 0,
          "duration": 6,
          "execution": -6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 22,
          "name": "Rocky Johnston",
          "difficulty": 21,
          "effect": 12,
          "form": "0",
          "area": 6,
          "duration": 3,
          "execution": 0,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 23,
          "name": "Britney Botsford",
          "difficulty": 18,
          "effect": 3,
          "form": "3",
          "area": 6,
          "duration": 6,
          "execution": 6,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 24,
          "name": "Noah Nolan",
          "difficulty": 6,
          "effect": 3,
          "form": "6",
          "area": 0,
          "duration": 0,
          "execution": -3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 25,
          "name": "Stan Kirlin",
          "difficulty": 15,
          "effect": 9,
          "form": "6",
          "area": 0,
          "duration": 3,
          "execution": 3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 26,
          "name": "Ethyl Mills",
          "difficulty": 6,
          "effect": 0,
          "form": "3",
          "area": 6,
          "duration": 6,
          "execution": -3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 27,
          "name": "Maudie Cronin",
          "difficulty": 21,
          "effect": 12,
          "form": "0",
          "area": 0,
          "duration": 6,
          "execution": 3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 28,
          "name": "Mrs. Earline Cummings IV",
          "difficulty": 6,
          "effect": 3,
          "form": "0",
          "area": 3,
          "duration": 3,
          "execution": 3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 29,
          "name": "Mrs. Vilma Schuppe",
          "difficulty": 18,
          "effect": 6,
          "form": "6",
          "area": 0,
          "duration": 0,
          "execution": 6,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 30,
          "name": "Jakayla Marvin V",
          "difficulty": 21,
          "effect": 12,
          "form": "3",
          "area": 3,
          "duration": 3,
          "execution": 0,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 31,
          "name": "Rachel Larson",
          "difficulty": 12,
          "effect": 15,
          "form": "6",
          "area": 0,
          "duration": 0,
          "execution": -6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 32,
          "name": "Corine Collier",
          "difficulty": 0,
          "effect": 6,
          "form": "3",
          "area": 0,
          "duration": 0,
          "execution": -3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 33,
          "name": "Carolanne Zemlak",
          "difficulty": -3,
          "effect": 0,
          "form": "0",
          "area": 0,
          "duration": 0,
          "execution": 3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 34,
          "name": "Dr. Deondre Jakubowski V",
          "difficulty": 9,
          "effect": 9,
          "form": "6",
          "area": 0,
          "duration": 6,
          "execution": -6,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 35,
          "name": "Kip West",
          "difficulty": 15,
          "effect": 6,
          "form": "0",
          "area": 6,
          "duration": 3,
          "execution": 6,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 36,
          "name": "Mr. Lavon Abshire",
          "difficulty": 12,
          "effect": 12,
          "form": "3",
          "area": 0,
          "duration": 0,
          "execution": 3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 37,
          "name": "Esther Gottlieb",
          "difficulty": 6,
          "effect": 9,
          "form": "0",
          "area": 6,
          "duration": 0,
          "execution": -6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 38,
          "name": "Dr. Eugenia Batz",
          "difficulty": 6,
          "effect": 9,
          "form": "3",
          "area": 6,
          "duration": 0,
          "execution": -6,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 39,
          "name": "Kathryn Walker",
          "difficulty": 15,
          "effect": 12,
          "form": "3",
          "area": 6,
          "duration": 3,
          "execution": -6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 40,
          "name": "Emmanuelle Dickinson I",
          "difficulty": 21,
          "effect": 15,
          "form": "0",
          "area": 0,
          "duration": 6,
          "execution": 0,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 41,
          "name": "Lyric Maggio",
          "difficulty": 15,
          "effect": 9,
          "form": "3",
          "area": 0,
          "duration": 3,
          "execution": 6,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 42,
          "name": "Florian Schmidt",
          "difficulty": 12,
          "effect": 0,
          "form": "0",
          "area": 3,
          "duration": 6,
          "execution": 3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 43,
          "name": "Erich Marvin",
          "difficulty": -3,
          "effect": 6,
          "form": "0",
          "area": 0,
          "duration": 0,
          "execution": -3,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 44,
          "name": "Clarissa Denesik PhD",
          "difficulty": 15,
          "effect": 0,
          "form": "3",
          "area": 6,
          "duration": 6,
          "execution": 0,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 45,
          "name": "Anais Kreiger",
          "difficulty": 9,
          "effect": 9,
          "form": "3",
          "area": 3,
          "duration": 0,
          "execution": 0,
          "restriction": -6,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 46,
          "name": "Aurelie Schaden",
          "difficulty": 18,
          "effect": 9,
          "form": "3",
          "area": 6,
          "duration": 6,
          "execution": -3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 47,
          "name": "Prof. Jovanny Pfeffer DVM",
          "difficulty": 18,
          "effect": 12,
          "form": "0",
          "area": 0,
          "duration": 0,
          "execution": 6,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 48,
          "name": "Osbaldo Casper",
          "difficulty": 0,
          "effect": 0,
          "form": "3",
          "area": 0,
          "duration": 6,
          "execution": -6,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 49,
          "name": "Cathrine Kessler",
          "difficulty": -3,
          "effect": 0,
          "form": "0",
          "area": 3,
          "duration": 0,
          "execution": -3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 50,
          "name": "Ludie Jakubowski",
          "difficulty": 15,
          "effect": 3,
          "form": "6",
          "area": 6,
          "duration": 6,
          "execution": -6,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 51,
          "name": "Dr. Annamae Mraz",
          "difficulty": 6,
          "effect": 6,
          "form": "3",
          "area": 0,
          "duration": 0,
          "execution": -3,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 52,
          "name": "Eleazar Huel",
          "difficulty": 24,
          "effect": 12,
          "form": "6",
          "area": 6,
          "duration": 6,
          "execution": -6,
          "restriction": 0,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 53,
          "name": "Mrs. Albertha Hansen Jr.",
          "difficulty": 18,
          "effect": 15,
          "form": "0",
          "area": 3,
          "duration": 6,
          "execution": -3,
          "restriction": -3,
          "description": "0",
          "created_at": "2018-07-16 23:06:43",
          "user_id": 1,
          "updated_at": "2018-07-16 23:06:43"
      },
      {
          "id": 54,
          "name": "Bola de Fogo",
          "difficulty": 15,
          "effect": 9,
          "form": "0",
          "area": 6,
          "duration": 0,
          "execution": 0,
          "restriction": 0,
          "description": "Bola de Fogo.",
          "created_at": "2018-07-17 00:15:39",
          "user_id": 1,
          "updated_at": "2018-07-17 00:15:39"
      }
  ]
  };

  // componentDidMount(){
  //   const techniques = TechniquesAPI.getAll();
  //   console.log(techniques);
  // }

  render() {

    const {techniques} = this.state;

    return (
      <div>
        <Route exact path="/" render={() =>(
          <Login/>
        )}/>

        <Route path="/register" render={() =>(
          <Register/>
        )}/>

        <Route exact path="/techniques" render={() =>(
          <div>
            <Menu active="techniques"/>
            <ListTechniques techniques={techniques} />
          </div>
        )}/>

        <Route exact path="/techniques/add" render={() =>(
          <div>
            <Menu active="techniques-add"/>
            <AddTechniques techniques={techniques} />
          </div>
        )}/>
      </div>      
    )
  }
}

export default App;